# Generated by Django 3.2.7 on 2021-10-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.category'),
        ),
    ]
