# Generated by Django 3.2.7 on 2021-10-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20211002_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='Category',
            new_name='category',
        ),
    ]
